id: ptt
title: "Pattern Test Ontology"
github_org: obophenotype
repo: ptt
report_fail_on: none
use_dosdps: TRUE
export_formats:
  - owl
  - obo
  - json
import_group:
  products:
    - id: ro
    - id: pato
pattern_pipelines_group:
  products:
    - id: manual
      dosdp_tools_options: "--obo-prefixes=true --restrict-axioms-to=logical"
    - id: auto
      dosdp_tools_options: "--obo-prefixes=true"